In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('base_eval.csv')

In [6]:
df.head()

,question,options,gold_text,gold_letter,pred_text,pred_letter,mcq_correct,exact_match,fuzzy_match,token_f1
0,A 21-year-old sexually active male complains o...,"['Chloramphenicol', 'Gentamicin', 'Ciprofloxac...",Ceftriaxone,D,D) Ceftriaxone\n\nExplanation:\nCeftriaxone is...,D,True,False,True,0.086957
1,A 5-year-old girl is brought to the emergency ...,"['Cyclic vomiting syndrome', 'Gastroenteritis'...",Cyclic vomiting syndrome,A,A) Cyclic vomiting syndrome\n\nExplanation:\n\...,A,True,False,True,0.214286
2,A 40-year-old woman presents with difficulty f...,"['Diazepam', 'St. John’s Wort', 'Paroxetine', ...",Trazodone,E,E) Trazodone\n\nTrazodone is an antidepressant...,E,True,False,True,0.062500
3,A 37-year-old female with a history of type II...,"['Obtain an abdominal CT scan', 'Obtain blood ...",Obtain a urine analysis and urine culture,C,B) Obtain blood cultures\n\nExplanation:\nThe ...,B,False,False,False,0.181818
4,A 19-year-old boy presents with confusion and ...,"['Hypoperfusion', 'Hyperglycemia', 'Metabolic ...",Hypoperfusion,A,A) Hypoperfusion\n\nExplanation:\nThe patient'...,A,True,False,True,0.074074

In [7]:
df_fine = pd.read_csv('finetune_full.csv')

In [8]:
df_fine.head()

,question,options,gold_text,gold_letter,pred_text,pred_letter,mcq_correct,exact_match,fuzzy_match,token_f1
0,A 21-year-old sexually active male complains o...,"['Chloramphenicol', 'Gentamicin', 'Ciprofloxac...",Ceftriaxone,D,Ciprofloxacin,C,False,False,False,0.0
1,A 5-year-old girl is brought to the emergency ...,"['Cyclic vomiting syndrome', 'Gastroenteritis'...",Cyclic vomiting syndrome,A,Cyclic vomiting syndrome,A,True,True,True,1.0
2,A 40-year-old woman presents with difficulty f...,"['Diazepam', 'St. John’s Wort', 'Paroxetine', ...",Trazodone,E,Paroxetine,C,False,False,False,0.0
3,A 37-year-old female with a history of type II...,"['Obtain an abdominal CT scan', 'Obtain blood ...",Obtain a urine analysis and urine culture,C,Obtain a urine analysis and urine culture,C,True,True,True,1.0
4,A 19-year-old boy presents with confusion and ...,"['Hypoperfusion', 'Hyperglycemia', 'Metabolic ...",Hypoperfusion,A,Hypophosphatemia,E,False,False,False,0.0

In [9]:
df_fine['mcq_correct'].sum() / 1272

np.float64(0.5)

In [21]:
df_fine[(df_fine['exact_match']==1) & (df_fine['mcq_correct']==0)].head(1)

,question,options,gold_text,gold_letter,pred_text,pred_letter,mcq_correct,exact_match,fuzzy_match,token_f1
7,"A 67-year-old man presents to the emergency department with a fever and altered mental status. The patient has a history of Alzheimer dementia and is typically bed bound. His son found him confused with a warm and flushed complexion thus prompting his presentation. The patient has a past medical history of dementia, diabetes, and hypertension and typically has a visiting home nurse come to administer medications. Prior to examination, he is given haloperidol and diphenhydramine as he is combative and will not allow the nurses near him. His temperature is 102.9°F (39.4°C), blood pressure is 104/64 mmHg, pulse is 170/min, respirations are 22/min, and oxygen saturation is 100% on room air. Physical exam is notable for dry and flushed skin and a confused man. There is no skin breakdown, and flexion of the patient’s neck elicits no discomfort. Laboratory studies are drawn as seen below.\n\nHemoglobin: 15 g/dL\nHematocrit: 45%\nLeukocyte count: 4,500/mm^3 with normal differential\nPlatelet count: 227,000/mm^3\n\nSerum:\nNa+: 139 mEq/L\nCl-: 100 mEq/L\nK+: 4.3 mEq/L\nHCO3-: 24 mEq/L\nBUN: 30 mg/dL\nGlucose: 97 mg/dL\nCreatinine: 1.5 mg/dL\nCa2+: 10.2 mg/dL\nAST: 12 U/L\nALT: 10 U/L\n\nUrine:\nColor: Yellow\nBacteria: Absent\nNitrites: Negative\nRed blood cells: Negative\n\nAn initial chest radiograph is unremarkable. The patient is given 3 liters of Ringer's lactate and an electric fan to cool off. Two hours later, his temperature is 99°F (37.2°C), blood pressure is 154/94 mmHg, pulse is 100/min, respirations are 17/min, and oxygen saturation is 100% on room air. The patient’s mental status is at the patient’s baseline according to the son. Which of the following is the most likely diagnosis?","['Exertional heat stroke', 'Neuroleptic malignant syndrome', 'Non-exertional heat stroke', 'Sepsis', 'Septic shock']",Non-exertional heat stroke,C,Non-exertional heat stroke,A,False,True,True,1.0

In [ ]:
from datasets import load_dataset

DATASET_ID = "bigbio/med_qa"
DATASET_CONFIG = "med_qa_en_source"
ds = load_dataset(DATASET_ID, DATASET_CONFIG, trust_remote_code=True)
train_ds = ds["train"]
val_ds = ds["validation"]

/home/tej/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading builder script: 11.1kB [00:00, 1.65MB/s]

{'meta_info': 'step1', 'question': 'A 21-year-old sexually active male complains of fever, pain during urination, and inflammation and pain in the right knee. A culture of the joint fluid shows a bacteria that does not ferment maltose and has no polysaccharide capsule. The physician orders antibiotic therapy for the patient. The mechanism of action of action of the medication given blocks cell wall synthesis, which of the following was given?', 'answer_idx': 'D', 'answer': 'Ceftriaxone', 'options': [{'key': 'A', 'value': 'Chloramphenicol'}, {'key': 'B', 'value': 'Gentamicin'}, {'key': 'C', 'value': 'Ciprofloxacin'}, {'key': 'D', 'value': 'Ceftriaxone'}, {'key': 'E', 'value': 'Trimethoprim'}]}

In [23]:
print(train_ds[0])

{'meta_info': 'step2&3', 'question': 'A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ago and has been worsening despite drinking more water and taking cranberry extract. She otherwise feels well and is followed by a doctor for her pregnancy. Her temperature is 97.7°F (36.5°C), blood pressure is 122/77 mmHg, pulse is 80/min, respirations are 19/min, and oxygen saturation is 98% on room air. Physical exam is notable for an absence of costovertebral angle tenderness and a gravid uterus. Which of the following is the best treatment for this patient?', 'answer_idx': 'E', 'answer': 'Nitrofurantoin', 'options': [{'key': 'A', 'value': 'Ampicillin'}, {'key': 'B', 'value': 'Ceftriaxone'}, {'key': 'C', 'value': 'Ciprofloxacin'}, {'key': 'D', 'value': 'Doxycycline'}, {'key': 'E', 'value': 'Nitrofurantoin'}]}

In [24]:
from datasets import load_dataset

def load_medqa_split(dataset_id="bigbio/med_qa", config="med_qa_en_source", split="validation"):
    """
    Loads MedQA dataset split.
    Returns a HuggingFace Dataset object.
    """
    ds = load_dataset(dataset_id, config)
    return ds[split]
val_ds = load_medqa_split()
print(val_ds[0])

/home/tej/miniconda3/envs/llama3/lib/python3.10/site-packages/datasets/load.py:1429: FutureWarning: The repository for bigbio/med_qa contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/bigbio/med_qa
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(

{'meta_info': 'step1', 'question': 'A 21-year-old sexually active male complains of fever, pain during urination, and inflammation and pain in the right knee. A culture of the joint fluid shows a bacteria that does not ferment maltose and has no polysaccharide capsule. The physician orders antibiotic therapy for the patient. The mechanism of action of action of the medication given blocks cell wall synthesis, which of the following was given?', 'answer_idx': 'D', 'answer': 'Ceftriaxone', 'options': [{'key': 'A', 'value': 'Chloramphenicol'}, {'key': 'B', 'value': 'Gentamicin'}, {'key': 'C', 'value': 'Ciprofloxacin'}, {'key': 'D', 'value': 'Ceftriaxone'}, {'key': 'E', 'value': 'Trimethoprim'}]}

In [25]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

def load_base_model(model_id):
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=False)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
    model.eval()

    return model, tokenizer

In [ ]:

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel


# -----------------------------------------------------------
# Helpers
# -----------------------------------------------------------
def load_base_model(model_id: str):
    """Load base CausalLM model + tokenizer."""
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=False)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
    model.eval()
    device = next(model.parameters()).device

    return model, tokenizer, device


def load_finetuned_model(model_id: str, lora_path: str):
    """Load base model and apply LoRA weights."""
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=False)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    base_model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
    model = PeftModel.from_pretrained(base_model, lora_path)
    model.eval()
    device = next(model.parameters()).device

    return model, tokenizer, device


# -----------------------------------------------------------
# Prediction function
# -----------------------------------------------------------
def generate_answer(
    model,
    tokenizer,
    device,
    prompt: str,
    max_new_tokens: int = 50,
    temperature: float = 0.0
):
    """Return ONLY the raw generated text."""
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=(temperature > 0),
        temperature=temperature if temperature > 0 else None,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )

    text = tokenizer.decode(out[0], skip_special_tokens=True)

    # Remove prompt from front
    if text.startswith(prompt):
        text = text[len(prompt):].strip()

    return text


# -----------------------------------------------------------
# Convenience functions
# -----------------------------------------------------------
def predict_base(model_id: str, prompt: str, max_new_tokens=50, temperature=0.0):
    model, tokenizer, device = load_base_model(model_id)
    return generate_answer(model, tokenizer, device, prompt, max_new_tokens, temperature)


def predict_finetuned(model_id: str, lora_path: str, prompt: str, max_new_tokens=50, temperature=0.0):
    model, tokenizer, device = load_finetuned_model(model_id, lora_path)
    return generate_answer(model, tokenizer, device, prompt, max_new_tokens, temperature)

In [28]:
prompt = "Question: What is 2+2?\nA) 3\nB) 4\nAnswer:"
print(predict_base("mistralai/Mistral-7B-Instruct-v0.3", prompt))

`torch_dtype` is deprecated! Use `dtype` instead!
Loading checkpoint shards: 100%|██████████| 3/3 [00:03<00:00,  1.13s/it]

B) 4

In [31]:
prompt = "Question: What is 2+2?\nA) 3\nB) 4\nAnswer:"
print(predict_finetuned(
    "mistralai/Mistral-7B-Instruct-v0.3",
    "qlora_medqa",
    prompt
))

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.38it/s]

4

In [32]:
def build_mcq_prompt(question, options):
    opts = "\n".join([f"{o['key']}) {o['value']}" for o in options])
    return f"Question: {question}\n{opts}\nAnswer:"

In [36]:
def predict_single(ex):
    prompt = build_mcq_prompt(ex["question"], ex["options"])

    base_pred = predict_base("mistralai/Mistral-7B-Instruct-v0.3", prompt)
    ft_pred   = predict_finetuned(
                "mistralai/Mistral-7B-Instruct-v0.3",
                "qlora_medqa",
                prompt)

    return {
        "prompt": prompt,
        "gold_letter": ex["answer_idx"],
        "gold_text": ex["answer"],
        "base_pred": base_pred,
        "ft_pred": ft_pred,
    }

In [37]:
ex = val_ds[0]
res = predict_single(ex)
print(res)

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.37it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.37it/s]

{'prompt': 'Question: A 21-year-old sexually active male complains of fever, pain during urination, and inflammation and pain in the right knee. A culture of the joint fluid shows a bacteria that does not ferment maltose and has no polysaccharide capsule. The physician orders antibiotic therapy for the patient. The mechanism of action of action of the medication given blocks cell wall synthesis, which of the following was given?\nA) Chloramphenicol\nB) Gentamicin\nC) Ciprofloxacin\nD) Ceftriaxone\nE) Trimethoprim\nAnswer:', 'gold_letter': 'D', 'gold_text': 'Ceftriaxone', 'base_pred': 'D) Ceftriaxone\n\nExplanation:\nCeftriaxone is a third-generation cephalosporin antibiotic that inhibits the synthesis of the bacterial cell wall. It does not', 'ft_pred': 'Ciprofloxacin'}

In [40]:
print(res['gold_letter'])
print(res['gold_text'])

D
Ceftriaxone

In [42]:
print(res['base_pred'])

D) Ceftriaxone

Explanation:
Ceftriaxone is a third-generation cephalosporin antibiotic that inhibits the synthesis of the bacterial cell wall. It does not

In [41]:
print(res['ft_pred'])

Ciprofloxacin

In [43]:
ex['options']

[{'key': 'A', 'value': 'Chloramphenicol'},
 {'key': 'B', 'value': 'Gentamicin'},
 {'key': 'C', 'value': 'Ciprofloxacin'},
 {'key': 'D', 'value': 'Ceftriaxone'},
 {'key': 'E', 'value': 'Trimethoprim'}]

In [20]:
from IPython.display import display

# show full text (no truncation) for string columns and allow viewing all columns/rows
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)  # WARNING: df_fine has 1272 rows; this will print them all

# display(df)        # display the 50-row dataframe with full text
# display(df_fine)   # display the 1272-row dataframe with full text

In [44]:
import numpy as np

In [48]:
np.argmin([len(val_ds[i]['question']) for i in range(len(val_ds))])

np.int64(779)

In [49]:
len(val_ds[779]['question'])

83

In [52]:
val_ds[779]

{'meta_info': 'step1',
 'question': 'In which location is dimeric IgA most likely to be found in highest concentrations?',
 'answer_idx': 'A',
 'answer': 'Colostrum',
 'options': [{'key': 'A', 'value': 'Colostrum'},
  {'key': 'B', 'value': 'Blood from the fetus'},
  {'key': 'C', 'value': 'Blood from the mother'},
  {'key': 'D', 'value': 'Fetal bone marrow'},
  {'key': 'E', 'value': 'Fetal thymus'}]}

In [53]:
sample_questions = val_ds[779]
res = predict_single(sample_questions)
for key, value in res.items():
    print(f"{key}: {value}\n")

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.34it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.26it/s]

prompt: Question: In which location is dimeric IgA most likely to be found in highest concentrations?
A) Colostrum
B) Blood from the fetus
C) Blood from the mother
D) Fetal bone marrow
E) Fetal thymus
Answer:

gold_letter: A

gold_text: Colostrum

base_pred: A) Colostrum

Explanation:
Dimeric IgA is a type of immunoglobulin that is primarily found in secretions such as colostrum, saliva, and tears. It plays a

ft_pred: Colostrum

In [59]:
# --- MAIN LOGIC ---

# 1. Calculate the length of the 'question' for every sample
question_lengths = np.array([len(sample['question']) for sample in val_ds])

# 2. Find the indices that would sort the array (ascending order)
# argsort returns the indices that sort the array. The first 10 indices
# correspond to the 10 shortest questions.
sorted_indices = np.argsort(question_lengths)

# 3. Select the indices of the top 10 shortest questions
shortest_10_indices = sorted_indices[:10]

print("-" * 50)
print(f"Total samples processed: {len(val_ds)}")
print(f"Top 10 Shortest Question Indices: {shortest_10_indices.tolist()}")
print("-" * 50)
print("\nProcessing the 10 Samples with the Least Question Length:\n")

# 4. Process each of the 10 shortest samples
for i, idx_np in enumerate(shortest_10_indices):
    idx = int(idx_np)
    sample = val_ds[idx]
    
    print(f"--- Sample {i+1}/10 (Index: {idx}, Length: {question_lengths[idx]}) ---")
    print(f"Question: {sample['question']}")
    
    # Run the prediction function
    res = predict_single(sample)
    
    # Print the prediction results
    print("\n[Prediction Results]")
    for key, value in res.items():
        # Ensure that the question key is not printed again in the prediction results section
        if key != 'question':
            print(f"{key}: {value}")
    
    print("-" * 50)

print("\nProcessing complete.")

--------------------------------------------------
Total samples processed: 1272
Top 10 Shortest Question Indices: [779, 224, 298, 335, 737, 839, 542, 660, 1265, 489]
--------------------------------------------------

Processing the 10 Samples with the Least Question Length:

--- Sample 1/10 (Index: 779, Length: 83) ---
Question: In which location is dimeric IgA most likely to be found in highest concentrations?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.30it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.31it/s]

[Prediction Results]
prompt: Question: In which location is dimeric IgA most likely to be found in highest concentrations?
A) Colostrum
B) Blood from the fetus
C) Blood from the mother
D) Fetal bone marrow
E) Fetal thymus
Answer:
gold_letter: A
gold_text: Colostrum
base_pred: A) Colostrum

Explanation:
Dimeric IgA is a type of immunoglobulin that is primarily found in secretions such as colostrum, saliva, and tears. It plays a
ft_pred: Colostrum
--------------------------------------------------
--- Sample 2/10 (Index: 224, Length: 88) ---
Question: Which of the following statements concerning positive predictive value (PPV) is correct?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.34it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.23it/s]

[Prediction Results]
prompt: Question: Which of the following statements concerning positive predictive value (PPV) is correct?
A) PPV is the proportion of tests that are true positives; if disease prevalence is low, then PPV will be low.
B) PPV is the proportion of tests that are true positives; if disease prevalence is high, then PPV will be low.
C) PPV is the proportion of tests that are true positives; disease prevalence has no effect on PPV.
D) PPV is the proportion of tests that are false positives; if disease prevalence is low, then PPV will be low.
E) PPV is the proportion of tests that are false positives; if disease prevalence is high then PPV will be low.
Answer:
gold_letter: A
gold_text: PPV is the proportion of tests that are true positives; if disease prevalence is low, then PPV will be low.
base_pred: A) PPV is the proportion of tests that are true positives; if disease prevalence is low, then PPV will be low.
ft_pred: PPV is the proportion of tests that are true positives; if disease prevalence is low, then PPV will be low.
--------------------------------------------------
--- Sample 3/10 (Index: 298, Length: 145) ---
Question: Which of the following trinucleotide DNA sequences would initiate protein translation when converted to mRNA?
Note: sequences are written 3'-->5'

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.36it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.35it/s]

[Prediction Results]
prompt: Question: Which of the following trinucleotide DNA sequences would initiate protein translation when converted to mRNA?
Note: sequences are written 3'-->5'
A) TAC
B) ACT
C) ATC
D) ATT
E) AAA
Answer:
gold_letter: A
gold_text: TAC
base_pred: D) ATT

Explanation:
The ATT sequence is the start codon for methionine in the genetic code. When this sequence is translated into mRNA, it will initiate protein synthesis. The other sequences
ft_pred: ATT
--------------------------------------------------
--- Sample 4/10 (Index: 335, Length: 148) ---
Question: A 28-year-old male is found to have 93% HbA, 2% HbF, and 5% HbA2 on hemoglobin electrophoresis. Which of the following is the most likely diagnosis?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.31it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.30it/s]

[Prediction Results]
prompt: Question: A 28-year-old male is found to have 93% HbA, 2% HbF, and 5% HbA2 on hemoglobin electrophoresis. Which of the following is the most likely diagnosis?
A) Sickle cell trait
B) Alpha thalassemia major with Hb Bart's
C) Beta-thalassemia minor
D) Beta-thalassemia major
E) Diabetes mellitus
Answer:
gold_letter: C
gold_text: Beta-thalassemia minor
base_pred: C) Beta-thalassemia minor

Explanation:

The presence of 93% HbA indicates normal or increased production of beta-globin chains. The presence of 2% HbF is consistent
ft_pred: Beta-thalassemia minor
--------------------------------------------------
--- Sample 5/10 (Index: 737, Length: 165) ---
Question: A thymic sample from a fetus is examined. One cell type found was double-positive for the CD4 and CD8 receptors. What is the identity of these double-positive cells?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.34it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.31it/s]

[Prediction Results]
prompt: Question: A thymic sample from a fetus is examined. One cell type found was double-positive for the CD4 and CD8 receptors. What is the identity of these double-positive cells?
A) T-cell progenitors cells in the bone marrow
B) B-cells
C) Immature T-cells of the thymic cortex
D) Immature T-cells of the thymic medulla
E) Macrophages
Answer:
gold_letter: C
gold_text: Immature T-cells of the thymic cortex
base_pred: C) Immature T-cells of the thymic cortex

Explanation:

Double-positive T cells (DP T cells) are T cells that express both CD4 and CD8 receptors on their
ft_pred: Immature T-cells of the thymic medulla
--------------------------------------------------
--- Sample 6/10 (Index: 839, Length: 165) ---
Question: An important step in the formation of thyroid hormones is the formation of I2 via oxidation of I-. Which of the following molecules is responsible for this reaction?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.34it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.35it/s]

[Prediction Results]
prompt: Question: An important step in the formation of thyroid hormones is the formation of I2 via oxidation of I-. Which of the following molecules is responsible for this reaction?
A) Thyroid deiodinase
B) Thyroid peroxidase
C) 5'-deiodinase
D) Perchlorate
E) Propylthiouracil
Answer:
gold_letter: B
gold_text: Thyroid peroxidase
base_pred: B) Thyroid peroxidase
ft_pred: Thyroid peroxidase
--------------------------------------------------
--- Sample 7/10 (Index: 542, Length: 175) ---
Question: A 56-year-old patient reports a history of recurrent dental caries. The bacteria causing this patient's dental problems most likely exhibits which of the following properties?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.33it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.27it/s]

[Prediction Results]
prompt: Question: A 56-year-old patient reports a history of recurrent dental caries. The bacteria causing this patient's dental problems most likely exhibits which of the following properties?
A) Inhibition of growth on optochin sensitivity test
B) Gram negative diplococci
C) Production of dextrans from glucose
D) Presence of catalase enzyme
E) Soluble in bile
Answer:
gold_letter: C
gold_text: Production of dextrans from glucose
base_pred: B) Gram negative diplococci

The bacteria most commonly associated with dental caries are Streptococcus mutans and Lactobacillus acidophilus. Both of these bacteria are Gram-positive,
ft_pred: Inhibition of growth on optochin sensitivity test
--------------------------------------------------
--- Sample 8/10 (Index: 660, Length: 189) ---
Question: A 60-year-old male painter with severe chest pain is found to have atherosclerosis of his coronary arteries. What type of cells were most likely injured in the initial stage of his disease?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.28it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.27it/s]

[Prediction Results]
prompt: Question: A 60-year-old male painter with severe chest pain is found to have atherosclerosis of his coronary arteries. What type of cells were most likely injured in the initial stage of his disease?
A) Myocytes
B) Fibroblasts
C) Neutrophils
D) Endothelial cells
E) Smooth muscle cells
Answer:
gold_letter: D
gold_text: Endothelial cells
base_pred: D) Endothelial cells

Explanation:

Atherosclerosis is a chronic inflammatory disease that affects the arterial walls. The initial stage of atherosclerosis involves the injury
ft_pred: Endothelial cells
--------------------------------------------------
--- Sample 9/10 (Index: 1265, Length: 191) ---
Question: A 48-year-old woman is admitted to the hospital and requires anticoagulation. She is administered a drug that binds tightly to antithrombin III. Which of the following drugs was administered?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.25it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.33it/s]

[Prediction Results]
prompt: Question: A 48-year-old woman is admitted to the hospital and requires anticoagulation. She is administered a drug that binds tightly to antithrombin III. Which of the following drugs was administered?
A) Aspirin
B) Warfarin
C) Dabigatran
D) Rivaroxaban
E) Enoxaparin
Answer:
gold_letter: E
gold_text: Enoxaparin
base_pred: C) Dabigatran

Dabigatran is a direct thrombin inhibitor that binds tightly to antithrombin III. Aspirin, warfarin, rivaroxaban, and enoxap
ft_pred: Enoxaparin
--------------------------------------------------
--- Sample 10/10 (Index: 489, Length: 208) ---
Question: A 39-year-old female was involved in a head-on collision motor vehicle accident. If she was found to have a traumatic rupture of the aorta, where along the path of the aorta is the most common site of injury?

Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.33it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.37it/s]

[Prediction Results]
prompt: Question: A 39-year-old female was involved in a head-on collision motor vehicle accident. If she was found to have a traumatic rupture of the aorta, where along the path of the aorta is the most common site of injury?
A) Ascending aorta
B) Site of attachment of ligamentum arteriosum
C) Aortic isthmus
D) Descending aorta - Thoracic aorta
E) Abdominal aorta
Answer:
gold_letter: C
gold_text: Aortic isthmus
base_pred: C) Aortic isthmus

The aortic isthmus is the narrowest part of the aorta, located between the left subclavian artery and the ductus arteriosus. It is
ft_pred: Aortic isthmus
--------------------------------------------------

Processing complete.